### ISSUE TITLE
Transaction history

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/open-dollar-app#19]
- Determine why historical transactions are not displayed for `Your transactions will appear here...` on profile

<img width="493" alt="Screen Shot 2023-07-21 at 4 23 25 PM" src="https://github.com/UseKeyp/open-dollar-app/assets/9449596/ba66ffe2-ddf1-4aeb-bbda-2b13d5e4dbf7">

**Comment by jahabeebs** [comment]
> * Determine why historical transactions are not displayed for `Your transactions will appear here...` on profile
> 
> 
> <img alt="Screen Shot 2023-07-21 at 4 23 25 PM" width="493" src="https://user-images.githubusercontent.com/9449596/255277195-ba66ffe2-ddf1-4aeb-bbda-2b13d5e4dbf7.png">

@pi0neerpat The reason the historical transactions aren't shown in a local environment is because the app is using state to manage past transactions. There isn't a query to the blockchain or a DB that populates the previous transactions. Currently, creating a safe is broken in the local environment so you haven't seen that transaction showing, but I've verified that the transaction shows up (on the deployed site) when you create a safe through https://www.letsgethai.com. If you want to see a transaction show up in your local environment, you can claim the test tokens (locally) and you'll be able to see it in your recent transactions. Also, these are only your recent transactions. Any transaction that happened more than a day ago won't be included.

## Screenshots

Recent transactions show up in local environment but will disappear once terminal process exited or a day has passed

<img width="663" alt="claim test tokens" src="https://github.com/UseKeyp/open-dollar-app/assets/47253537/d7310ab2-522b-4b7c-87a7-129f8763f0db">

Safe creation and test token claiming shows up in the deployed site

<img width="872" alt="deployedsite" src="https://github.com/UseKeyp/open-dollar-app/assets/47253537/67cb4184-008f-41d7-97ac-4b2483649ef4">

**Comment by pi0neerpat** [comment]
Closing as no change is necessary
